In [1]:
!pip install pandas

Requirement already satisfied: pandas in d:\pandas\projects\c_project\venv\lib\site-packages (2.3.3)
Requirement already satisfied: numpy>=1.22.4 in d:\pandas\projects\c_project\venv\lib\site-packages (from pandas) (2.0.2)
Requirement already satisfied: pytz>=2020.1 in d:\pandas\projects\c_project\venv\lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: tzdata>=2022.7 in d:\pandas\projects\c_project\venv\lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: python-dateutil>=2.8.2 in d:\pandas\projects\c_project\venv\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in d:\pandas\projects\c_project\venv\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

WARNING: You are using pip version 21.2.4; however, version 26.0.1 is available.
You should consider upgrading via the 'D:\pandas\Projects\c_project\venv\Scripts\python.exe -m pip install --upgrade pip' command.

In [1]:
import pandas as pd

In [3]:
df = pd.read_csv('D:\pandas\Projects\c_project\customer_shopping_behavior.csv')
df.head(5)

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             3900 non-null   int64
 1   Age                     3900 non-null   int64
 2   Gender                  3900 non-null   object
 3   Item Purchased          3900 non-null   object
 4   Category                3900 non-null   object
 5   Purchase Amount (USD)   3900 non-null   int64
 6   Location                3900 non-null   object
 7   Size                    3900 non-null   object
 8   Color                   3900 non-null   object
 9   Season                  3900 non-null   object
 10  Review Rating           3863 non-null   float64
 11  Subscription Status     3900 non-null   object
 12  Shipping Type           3900 non-null   object
 13  Discount Applied        3900 non-null   object
 14  Promo Code Used         3900 non-null   object
 15  Previous Purchases      3900 non-null   int64
 16  Payment Method          3900 non-null   object
 17  Frequency of Purchases  3900 non-null   object
dtypes: float64(1), int64(4), object(13)
memory usage: 548.6+ KB

In [5]:
df.describe()

,Customer ID,Age,Purchase Amount (USD),Review Rating,Previous Purchases
count,3900.000000,3900.000000,3900.000000,3863.000000,3900.000000
mean,1950.500000,44.068462,59.764359,3.750065,25.351538
std,1125.977353,15.207589,23.685392,0.716983,14.447125
min,1.000000,18.000000,20.000000,2.500000,1.000000
25%,975.750000,31.000000,39.000000,3.100000,13.000000
50%,1950.500000,44.000000,60.000000,3.800000,25.000000
75%,2925.250000,57.000000,81.000000,4.400000,38.000000
max,3900.000000,70.000000,100.000000,5.000000,50.000000

In [6]:
df.isnull().sum()

Customer ID                0
Age                        0
Gender                     0
Item Purchased             0
Category                   0
Purchase Amount (USD)      0
Location                   0
Size                       0
Color                      0
Season                     0
Review Rating             37
Subscription Status        0
Shipping Type              0
Discount Applied           0
Promo Code Used            0
Previous Purchases         0
Payment Method             0
Frequency of Purchases     0
dtype: int64

In [7]:
df['Review Rating']=df.groupby('Category')['Review Rating'].transform(lambda x: x.fillna(x.median()))

In [8]:
df.isnull().sum()

Customer ID               0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
Purchase Amount (USD)     0
Location                  0
Size                      0
Color                     0
Season                    0
Review Rating             0
Subscription Status       0
Shipping Type             0
Discount Applied          0
Promo Code Used           0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
dtype: int64

In [32]:
df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(' ', '_')

In [34]:
df.columns = [
    'customer_id',
    'age',
    'gender',
    'item_purchased',
    'category',
    'purchase_amount_usd',
    'location',
    'size',
    'color',
    'season',
    'review_rating',
    'subscription_status',
    'shipping_type',
    'discount_applied',
    'promo_code_used',
    'previous_purchases',
    'payment_method',
    'frequency_of_purchases'
]

In [35]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount_usd', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='object')

create a new age_group

In [36]:
labels = ['young Adult','Adult','middle Age','Senior']
df['age_group']=pd.qcut(df['age'],q=4,labels=labels)

In [38]:
df[['age','age_group']].head(10)

   age    age_group
0   55   middle Age
1   19  young Adult
2   50   middle Age
3   21  young Adult
4   45   middle Age
5   46   middle Age
6   63       Senior
7   27  young Adult
8   26  young Adult
9   57   middle Age

Purchase frequency_day

In [43]:
df.head(5)

,customer_id,age,gender,item_purchased,category,purchase_amount_usd,location,size,color,season,review_rating,subscription_status,shipping_type,discount_applied,promo_code_used,previous_purchases,payment_method,frequency_of_purchases,age_group
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly,middle Age
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly,young Adult
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly,middle Age
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly,young Adult
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually,middle Age

In [44]:
frequency_mapping={
    'Fortnightly':14,
    'Weekly':7,
    'Annually':365,
    'Quarterly':90,
    'Bi-Weekly':14,
    'Monthly':30,
    'Every 3 Months':90
}
df['purchases_frequency_days']=df['frequency_of_purchases'].map(frequency_mapping)

In [45]:
df[['purchases_frequency_days','frequency_of_purchases']].head(10)

   purchases_frequency_days frequency_of_purchases
0                        14            Fortnightly
1                        14            Fortnightly
2                         7                 Weekly
3                         7                 Weekly
4                       365               Annually
5                         7                 Weekly
6                        90              Quarterly
7                         7                 Weekly
8                       365               Annually
9                        90              Quarterly

In [46]:
df.head(5)

,customer_id,age,gender,item_purchased,category,purchase_amount_usd,location,size,color,season,review_rating,subscription_status,shipping_type,discount_applied,promo_code_used,previous_purchases,payment_method,frequency_of_purchases,age_group,purchases_frequency_days
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly,middle Age,14
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly,young Adult,14
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly,middle Age,7
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly,young Adult,7
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually,middle Age,365

In [47]:
(df['discount_applied']==df['promo_code_used']).all()

np.True_

In [48]:
df = df.drop('promo_code_used',axis=1)

In [49]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount_usd', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'previous_purchases', 'payment_method',
       'frequency_of_purchases', 'age_group', 'purchases_frequency_days'],
      dtype='object')

In [50]:
!pip install psycopg2.binary sqlalchemy

Collecting psycopg2.binary
  Downloading psycopg2_binary-2.9.12-cp39-cp39-win_amd64.whl (2.8 MB)
Collecting sqlalchemy
  Using cached sqlalchemy-2.0.49-cp39-cp39-win_amd64.whl (2.1 MB)
Collecting greenlet>=1
  Using cached greenlet-3.2.5.tar.gz (191 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
    Preparing wheel metadata: started
    Preparing wheel metadata: finished with status 'done'
Requirement already satisfied: typing-extensions>=4.6.0 in d:\pandas\projects\c_project\venv\lib\site-packages (from sqlalchemy) (4.15.0)
Building wheels for collected packages: greenlet
  Building wheel for greenlet (PEP 517): started
  Building wheel for greenlet (PEP 517): finished with status 'error'
Failed to build greenlet

  ERROR: Command errored out with exit status 1:
   command: 'D:\pandas\Projects\c_project\venv\Scripts\python.exe' 'D:\pandas\Projects\c_project\venv\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py' build_wheel 'C:\Users\ankit\AppData\Local\Temp\tmpdaosj6_l'
       cwd: C:\Users\ankit\AppData\Local\Temp\pip-install-fe9l4txq\greenlet_823c319b9c204da69cfdc050dc2a1065
  Complete output (112 lines):
  running bdist_wheel
  running build
  running build_py
  creating build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\__init__.py -> build\lib.win-amd64-cpython-39\greenlet
  creating build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\__init__.py -> build\lib.win-amd64-cpython-39\greenlet\platform
  creating build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\fail_clearing_run_switches.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\fail_cpp_exception.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\fail_initialstub_already_started.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\fail_slp_switch.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\fail_switch_three_greenlets.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\fail_switch_three_greenlets2.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\fail_switch_two_greenlets.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\leakcheck.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\test_contextvars.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\test_cpp.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\test_extension_interface.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\test_gc.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\test_generator.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\test_generator_nested.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\test_greenlet.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\test_greenlet_trash.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\test_interpreter_shutdown.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\test_leaks.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\test_stack_saved.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\test_throw.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\test_tracing.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\test_version.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\test_weakref.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\__init__.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  running egg_info
  writing src\greenlet.egg-info\PKG-INFO
  writing dependency_links to src\greenlet.egg-info\dependency_links.txt
  writing requirements to src\greenlet.egg-info\requires.txt
  writing top-level names to src\greenlet.egg-info\top_level.txt
  reading manifest file 'src\greenlet.egg-info\SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  warning: no previously-included files found matching 'benchmarks\*.json'
  no previously-included directories found matching 'docs\_build'
  warning: no files found matching '*.py' under directory 'appveyor'
  warning: no previously-included files matching '*.pyc' found anywhere in distribution
  warning: no previously-included files matching '*.pyd' found anywhere in distribution
  warning: no previously-included files matching '*.so' found anywhere in distribution
  warning: no previously-included files matching '.coverage' found anywhere in distribution
  adding license file 'LICENSE'
  adding license file 'LICENSE.PSF'
  writing manifest file 'src\greenlet.egg-info\SOURCES.txt'
  copying src\greenlet\CObjects.cpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\PyGreenlet.cpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\PyGreenlet.hpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\PyGreenletUnswitchable.cpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\PyModule.cpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\TBrokenGreenlet.cpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\TExceptionState.cpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\TGreenlet.cpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\TGreenlet.hpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\TGreenletGlobals.cpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\TMainGreenlet.cpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\TPythonState.cpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\TStackState.cpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\TThreadState.hpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\TThreadStateCreator.hpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\TThreadStateDestroy.cpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\TUserGreenlet.cpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\greenlet.cpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\greenlet.h -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\greenlet_allocator.hpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\greenlet_compiler_compat.hpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\greenlet_cpython_compat.hpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\greenlet_exceptions.hpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\greenlet_internal.hpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\greenlet_msvc_compat.hpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\greenlet_refs.hpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\greenlet_slp_switch.hpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\greenlet_thread_support.hpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\slp_platformselect.h -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\platform\setup_switch_x64_masm.cmd -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_aarch64_gcc.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_alpha_unix.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_amd64_unix.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_arm32_gcc.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_arm32_ios.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_arm64_masm.asm -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_arm64_masm.obj -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_arm64_msvc.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_csky_gcc.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_loongarch64_linux.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_m68k_gcc.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_mips_unix.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_ppc64_aix.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_ppc64_linux.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_ppc_aix.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_ppc_linux.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_ppc_macosx.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_ppc_unix.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_riscv_unix.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_s390_unix.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_sh_gcc.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_sparc_sun_gcc.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_x32_unix.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_x64_masm.asm -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_x64_masm.obj -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_x64_msvc.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_x86_msvc.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_x86_unix.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\tests\_test_extension.c -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\_test_extension_cpp.cpp -> build\lib.win-amd64-cpython-39\greenlet\tests
  running build_ext
  building 'greenlet._greenlet' extension
  error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
  ----------------------------------------
  ERROR: Failed building wheel for greenlet
ERROR: Could not build wheels for greenlet which use PEP 517 and cannot be installed directly
WARNING: You are using pip version 21.2.4; however, version 26.0.1 is available.
You should consider upgrading via the 'D:\pandas\Projects\c_project\venv\Scripts\python.exe -m pip install --upgrade pip' command.

In [51]:
!pip install psycopg2-binary sqlalchemy

Collecting psycopg2-binary
  Using cached psycopg2_binary-2.9.12-cp39-cp39-win_amd64.whl (2.8 MB)
Collecting sqlalchemy
  Using cached sqlalchemy-2.0.49-cp39-cp39-win_amd64.whl (2.1 MB)
Collecting greenlet>=1
  Using cached greenlet-3.2.5.tar.gz (191 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
    Preparing wheel metadata: started
    Preparing wheel metadata: finished with status 'done'
Requirement already satisfied: typing-extensions>=4.6.0 in d:\pandas\projects\c_project\venv\lib\site-packages (from sqlalchemy) (4.15.0)
Building wheels for collected packages: greenlet
  Building wheel for greenlet (PEP 517): started
  Building wheel for greenlet (PEP 517): finished with status 'error'
Failed to build greenlet

  ERROR: Command errored out with exit status 1:
   command: 'D:\pandas\Projects\c_project\venv\Scripts\python.exe' 'D:\pandas\Projects\c_project\venv\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py' build_wheel 'C:\Users\ankit\AppData\Local\Temp\tmpj27hitl3'
       cwd: C:\Users\ankit\AppData\Local\Temp\pip-install-xznvaem5\greenlet_d92855dcc74f4068a45f09a97c29a912
  Complete output (112 lines):
  running bdist_wheel
  running build
  running build_py
  creating build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\__init__.py -> build\lib.win-amd64-cpython-39\greenlet
  creating build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\__init__.py -> build\lib.win-amd64-cpython-39\greenlet\platform
  creating build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\fail_clearing_run_switches.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\fail_cpp_exception.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\fail_initialstub_already_started.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\fail_slp_switch.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\fail_switch_three_greenlets.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\fail_switch_three_greenlets2.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\fail_switch_two_greenlets.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\leakcheck.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\test_contextvars.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\test_cpp.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\test_extension_interface.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\test_gc.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\test_generator.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\test_generator_nested.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\test_greenlet.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\test_greenlet_trash.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\test_interpreter_shutdown.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\test_leaks.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\test_stack_saved.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\test_throw.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\test_tracing.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\test_version.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\test_weakref.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\__init__.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  running egg_info
  writing src\greenlet.egg-info\PKG-INFO
  writing dependency_links to src\greenlet.egg-info\dependency_links.txt
  writing requirements to src\greenlet.egg-info\requires.txt
  writing top-level names to src\greenlet.egg-info\top_level.txt
  reading manifest file 'src\greenlet.egg-info\SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  warning: no previously-included files found matching 'benchmarks\*.json'
  no previously-included directories found matching 'docs\_build'
  warning: no files found matching '*.py' under directory 'appveyor'
  warning: no previously-included files matching '*.pyc' found anywhere in distribution
  warning: no previously-included files matching '*.pyd' found anywhere in distribution
  warning: no previously-included files matching '*.so' found anywhere in distribution
  warning: no previously-included files matching '.coverage' found anywhere in distribution
  adding license file 'LICENSE'
  adding license file 'LICENSE.PSF'
  writing manifest file 'src\greenlet.egg-info\SOURCES.txt'
  copying src\greenlet\CObjects.cpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\PyGreenlet.cpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\PyGreenlet.hpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\PyGreenletUnswitchable.cpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\PyModule.cpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\TBrokenGreenlet.cpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\TExceptionState.cpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\TGreenlet.cpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\TGreenlet.hpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\TGreenletGlobals.cpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\TMainGreenlet.cpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\TPythonState.cpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\TStackState.cpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\TThreadState.hpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\TThreadStateCreator.hpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\TThreadStateDestroy.cpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\TUserGreenlet.cpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\greenlet.cpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\greenlet.h -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\greenlet_allocator.hpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\greenlet_compiler_compat.hpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\greenlet_cpython_compat.hpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\greenlet_exceptions.hpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\greenlet_internal.hpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\greenlet_msvc_compat.hpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\greenlet_refs.hpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\greenlet_slp_switch.hpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\greenlet_thread_support.hpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\slp_platformselect.h -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\platform\setup_switch_x64_masm.cmd -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_aarch64_gcc.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_alpha_unix.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_amd64_unix.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_arm32_gcc.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_arm32_ios.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_arm64_masm.asm -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_arm64_masm.obj -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_arm64_msvc.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_csky_gcc.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_loongarch64_linux.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_m68k_gcc.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_mips_unix.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_ppc64_aix.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_ppc64_linux.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_ppc_aix.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_ppc_linux.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_ppc_macosx.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_ppc_unix.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_riscv_unix.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_s390_unix.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_sh_gcc.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_sparc_sun_gcc.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_x32_unix.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_x64_masm.asm -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_x64_masm.obj -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_x64_msvc.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_x86_msvc.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_x86_unix.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\tests\_test_extension.c -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\_test_extension_cpp.cpp -> build\lib.win-amd64-cpython-39\greenlet\tests
  running build_ext
  building 'greenlet._greenlet' extension
  error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
  ----------------------------------------
  ERROR: Failed building wheel for greenlet
ERROR: Could not build wheels for greenlet which use PEP 517 and cannot be installed directly
WARNING: You are using pip version 21.2.4; however, version 26.0.1 is available.
You should consider upgrading via the 'D:\pandas\Projects\c_project\venv\Scripts\python.exe -m pip install --upgrade pip' command.

In [52]:
!python -m pip install --upgrade pip

Requirement already satisfied: pip in d:\pandas\projects\c_project\venv\lib\site-packages (21.2.4)
Collecting pip
  Using cached pip-26.0.1-py3-none-any.whl (1.8 MB)
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 21.2.4
    Uninstalling pip-21.2.4:
      Successfully uninstalled pip-21.2.4
Successfully installed pip-26.0.1

In [54]:
!pip install wheel setuptools

Requirement already satisfied: wheel in .\venv\lib\site-packages (0.47.0)
Requirement already satisfied: setuptools in .\venv\lib\site-packages (58.1.0)
Requirement already satisfied: packaging>=24.0 in .\venv\lib\site-packages (from wheel) (26.2)

In [55]:
!pip install greenlet==1.1.3

Collecting greenlet==1.1.3
  Downloading greenlet-1.1.3-cp39-cp39-win_amd64.whl.metadata (3.9 kB)
Downloading greenlet-1.1.3-cp39-cp39-win_amd64.whl (101 kB)
Installing collected packages: greenlet
Successfully installed greenlet-1.1.3

In [56]:
!pip install sqlalchemy

Collecting sqlalchemy
  Downloading sqlalchemy-2.0.49-cp39-cp39-win_amd64.whl.metadata (9.8 kB)
Requirement already satisfied: greenlet>=1 in .\venv\lib\site-packages (from sqlalchemy) (1.1.3)
Requirement already satisfied: typing-extensions>=4.6.0 in .\venv\lib\site-packages (from sqlalchemy) (4.15.0)
Downloading sqlalchemy-2.0.49-cp39-cp39-win_amd64.whl (2.1 MB)
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.1 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.1 MB ? eta -:--:--
   --------- ------------------------------ 0.5/2.1 MB 699.0 kB/s eta 0:00:03
   -------------- ------------------------- 0.8/2.1 MB 907.1 kB/s eta 0:00:02
   -------------- ------------------------- 0.8/2.1 MB 907.1 kB/s eta 0:00:02
   -------------- ------------------------- 0.8/2.1 MB 907.1 kB/s eta 0:00:02
   ------------------- -------------------- 1.0/2.1 MB 680.3 kB/s eta 0:00:02
   ------------------------ --------------- 1.3/2.1 MB 762.6 kB/s eta 0:00:02
   ------------------------ --------------- 1.3/2.1 MB 762.6 kB/s eta 0:00:02
   ------------------------ --------------- 1.3/2.1 MB 762.6 kB/s eta 0:00:02
   ------------------------ --------------- 1.3/2.1 MB 762.6 kB/s eta 0:00:02
   ----------------------------- ---------- 1.6/2.1 MB 548.4 kB/s eta 0:00:02
   ----------------------------- ---------- 1.6/2.1 MB 548.4 kB/s eta 0:00:02
   ---------------------------------- ----- 1.8/2.1 MB 588.6 kB/s eta 0:00:01
   ---------------------------------------- 2.1/2.1 MB 611.7 kB/s  0:00:03
Installing collected packages: sqlalchemy
Successfully installed sqlalchemy-2.0.49

In [57]:
!pip install psycopg2-binary

Collecting psycopg2-binary
  Downloading psycopg2_binary-2.9.12-cp39-cp39-win_amd64.whl.metadata (5.1 kB)
Downloading psycopg2_binary-2.9.12-cp39-cp39-win_amd64.whl (2.8 MB)
   ---------------------------------------- 0.0/2.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.8 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.8 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.8 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.8 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.8 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.8 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.8 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.8 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.8 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.8 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.8 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.8 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.8 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.8 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.8 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.8 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.8 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.8 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.8 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.8 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.8 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.8 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.8 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.8 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.8 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.8 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.8 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.8 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.8 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.8 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.8 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.8 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.8 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.8 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.8 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.8 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.8 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.8 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.8 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.8 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.8 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.8 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.8 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.8 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.8 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.8 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.8 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.8 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.8 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.8 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.8 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.8 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.8 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.8 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.8 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.8 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.8 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.8 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.8 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.8 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.8 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.8 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.8 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.8 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.8 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.8 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.8 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.8 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.8 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.8 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.8 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.8 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.8 MB ? eta -:--:--
Resuming download psycopg2_binary-2.9.12-cp39-cp39-win_amd64.whl (262 kB/2.8 MB)
   --- ------------------------------------ 0.3/2.8 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.8 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.8 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.8 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.8 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.8 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.8 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.8 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.8 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.8 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.8 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.8 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.8 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.8 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.8 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.8 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.8 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.8 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.8 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.8 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.8 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.8 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.8 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.8 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.8 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.8 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.8 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.8 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.8 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.8 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.8 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.8 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.8 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.8 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.8 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.8 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.8 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.8 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.8 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.8 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.8 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.8 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.8 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.8 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.8 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.8 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.8 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.8 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.8 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.8 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.8 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.8 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.8 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.8 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.8 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.8 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.8 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.8 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.8 MB ? eta -:--:--
   ------- -------------------------------- 0.5/2.8 MB 21.0 kB/s eta 0:01:47
   ------- -------------------------------- 0.5/2.8 MB 21.0 kB/s eta 0:01:47
   ------- -------------------------------- 0.5/2.8 MB 21.0 kB/s eta 0:01:47
   ------- -------------------------------- 0.5/2.8 MB 21.0 kB/s eta 0:01:47
   ------- -------------------------------- 0.5/2.8 MB 21.0 kB/s eta 0:01:47
   ------- -------------------------------- 0.5/2.8 MB 21.0 kB/s eta 0:01:47
   ------- -------------------------------- 0.5/2.8 MB 21.0 kB/s eta 0:01:47
   ------- -------------------------------- 0.5/2.8 MB 21.0 kB/s eta 0:01:47
   ------- -------------------------------- 0.5/2.8 MB 21.0 kB/s eta 0:01:47
   ------- -------------------------------- 0.5/2.8 MB 21.0 kB/s eta 0:01:47
   ------- -------------------------------- 0.5/2.8 MB 21.0 kB/s eta 0:01:47
   ------- -------------------------------- 0.5/2.8 MB 21.0 kB/s eta 0:01:47
   ------- -------------------------------- 0.5/2.8 MB 21.0 kB/s eta 0:01:47
   ------- -------------------------------- 0.5/2.8 MB 21.0 kB/s eta 0:01:47
   ------- -------------------------------- 0.5/2.8 MB 21.0 kB/s eta 0:01:47
   ------- -------------------------------- 0.5/2.8 MB 21.0 kB/s eta 0:01:47
   ----------- ---------------------------- 0.8/2.8 MB 32.9 kB/s eta 0:01:00
   ----------- ---------------------------- 0.8/2.8 MB 32.9 kB/s eta 0:01:00
   ----------- ---------------------------- 0.8/2.8 MB 32.9 kB/s eta 0:01:00
   ----------- ---------------------------- 0.8/2.8 MB 32.9 kB/s eta 0:01:00
   ----------- ---------------------------- 0.8/2.8 MB 32.9 kB/s eta 0:01:00
   ----------- ---------------------------- 0.8/2.8 MB 32.9 kB/s eta 0:01:00
   ----------- ---------------------------- 0.8/2.8 MB 32.9 kB/s eta 0:01:00
   ----------- ---------------------------- 0.8/2.8 MB 32.9 kB/s eta 0:01:00
   ----------- ---------------------------- 0.8/2.8 MB 32.9 kB/s eta 0:01:00
   ----------- ---------------------------- 0.8/2.8 MB 32.9 kB/s eta 0:01:00
   ----------- ---------------------------- 0.8/2.8 MB 32.9 kB/s eta 0:01:00
   ----------- ---------------------------- 0.8/2.8 MB 32.9 kB/s eta 0:01:00
   ----------- ---------------------------- 0.8/2.8 MB 32.9 kB/s eta 0:01:00
   ----------- ---------------------------- 0.8/2.8 MB 32.9 kB/s eta 0:01:00
   ----------- ---------------------------- 0.8/2.8 MB 32.9 kB/s eta 0:01:00
   ----------- ---------------------------- 0.8/2.8 MB 32.9 kB/s eta 0:01:00
   ----------- ---------------------------- 0.8/2.8 MB 32.9 kB/s eta 0:01:00
   ----------- ---------------------------- 0.8/2.8 MB 32.9 kB/s eta 0:01:00
   ----------- ---------------------------- 0.8/2.8 MB 32.9 kB/s eta 0:01:00
   ----------- ---------------------------- 0.8/2.8 MB 32.9 kB/s eta 0:01:00
   ----------- ---------------------------- 0.8/2.8 MB 32.9 kB/s eta 0:01:00
   ----------- ---------------------------- 0.8/2.8 MB 32.9 kB/s eta 0:01:00
   ----------- ---------------------------- 0.8/2.8 MB 32.9 kB/s eta 0:01:00
   ----------- ---------------------------- 0.8/2.8 MB 32.9 kB/s eta 0:01:00
   ----------- ---------------------------- 0.8/2.8 MB 32.9 kB/s eta 0:01:00
   ----------- ---------------------------- 0.8/2.8 MB 32.9 kB/s eta 0:01:00
   ----------- ---------------------------- 0.8/2.8 MB 32.9 kB/s eta 0:01:00
   ----------- ---------------------------- 0.8/2.8 MB 32.9 kB/s eta 0:01:00
   ----------- ---------------------------- 0.8/2.8 MB 32.9 kB/s eta 0:01:00
   --------------- ------------------------ 1.0/2.8 MB 35.6 kB/s eta 0:00:49
   --------------- ------------------------ 1.0/2.8 MB 35.6 kB/s eta 0:00:49
   --------------- ------------------------ 1.0/2.8 MB 35.6 kB/s eta 0:00:49
   --------------- ------------------------ 1.0/2.8 MB 35.6 kB/s eta 0:00:49
   --------------- ------------------------ 1.0/2.8 MB 35.6 kB/s eta 0:00:49
   --------------- ------------------------ 1.0/2.8 MB 35.6 kB/s eta 0:00:49
   --------------- ------------------------ 1.0/2.8 MB 35.6 kB/s eta 0:00:49
   --------------- ------------------------ 1.0/2.8 MB 35.6 kB/s eta 0:00:49
   --------------- ------------------------ 1.0/2.8 MB 35.6 kB/s eta 0:00:49
   --------------- ------------------------ 1.0/2.8 MB 35.6 kB/s eta 0:00:49
   --------------- ------------------------ 1.0/2.8 MB 35.6 kB/s eta 0:00:49
   --------------- ------------------------ 1.0/2.8 MB 35.6 kB/s eta 0:00:49
   --------------- ------------------------ 1.0/2.8 MB 35.6 kB/s eta 0:00:49
   --------------- ------------------------ 1.0/2.8 MB 35.6 kB/s eta 0:00:49
   --------------- ------------------------ 1.0/2.8 MB 35.6 kB/s eta 0:00:49
   --------------- ------------------------ 1.0/2.8 MB 35.6 kB/s eta 0:00:49
   --------------- ------------------------ 1.0/2.8 MB 35.6 kB/s eta 0:00:49
   --------------- ------------------------ 1.0/2.8 MB 35.6 kB/s eta 0:00:49
   --------------- ------------------------ 1.0/2.8 MB 35.6 kB/s eta 0:00:49
   --------------- ------------------------ 1.0/2.8 MB 35.6 kB/s eta 0:00:49
   --------------- ------------------------ 1.0/2.8 MB 35.6 kB/s eta 0:00:49
   --------------- ------------------------ 1.0/2.8 MB 35.6 kB/s eta 0:00:49
   --------------- ------------------------ 1.0/2.8 MB 35.6 kB/s eta 0:00:49
   --------------- ------------------------ 1.0/2.8 MB 35.6 kB/s eta 0:00:49
   --------------- ------------------------ 1.0/2.8 MB 35.6 kB/s eta 0:00:49
   --------------- ------------------------ 1.0/2.8 MB 35.6 kB/s eta 0:00:49
   --------------- ------------------------ 1.0/2.8 MB 35.6 kB/s eta 0:00:49
   --------------- ------------------------ 1.0/2.8 MB 35.6 kB/s eta 0:00:49
   --------------- ------------------------ 1.0/2.8 MB 35.6 kB/s eta 0:00:49
   --------------- ------------------------ 1.0/2.8 MB 35.6 kB/s eta 0:00:49
   --------------- ------------------------ 1.0/2.8 MB 35.6 kB/s eta 0:00:49
   --------------- ------------------------ 1.0/2.8 MB 35.6 kB/s eta 0:00:49
   --------------- ------------------------ 1.0/2.8 MB 35.6 kB/s eta 0:00:49
   --------------- ------------------------ 1.0/2.8 MB 35.6 kB/s eta 0:00:49
   --------------- ------------------------ 1.0/2.8 MB 35.6 kB/s eta 0:00:49
   --------------- ------------------------ 1.0/2.8 MB 35.6 kB/s eta 0:00:49
   --------------- ------------------------ 1.0/2.8 MB 35.6 kB/s eta 0:00:49
   --------------- ------------------------ 1.0/2.8 MB 35.6 kB/s eta 0:00:49
   --------------- ------------------------ 1.0/2.8 MB 35.6 kB/s eta 0:00:49
   --------------- ------------------------ 1.0/2.8 MB 35.6 kB/s eta 0:00:49
   --------------- ------------------------ 1.0/2.8 MB 35.6 kB/s eta 0:00:49
   --------------- ------------------------ 1.0/2.8 MB 35.6 kB/s eta 0:00:49
   --------------- ------------------------ 1.0/2.8 MB 35.6 kB/s eta 0:00:49
   --------------- ------------------------ 1.0/2.8 MB 35.6 kB/s eta 0:00:49
   --------------- ------------------------ 1.0/2.8 MB 35.6 kB/s eta 0:00:49
   --------------- ------------------------ 1.0/2.8 MB 35.6 kB/s eta 0:00:49
   --------------- ------------------------ 1.0/2.8 MB 35.6 kB/s eta 0:00:49
   --------------- ------------------------ 1.0/2.8 MB 35.6 kB/s eta 0:00:49
   ------------------- -------------------- 1.3/2.8 MB 39.2 kB/s eta 0:00:37
   ------------------- -------------------- 1.3/2.8 MB 39.2 kB/s eta 0:00:37
   ------------------- -------------------- 1.3/2.8 MB 39.2 kB/s eta 0:00:37
   ------------------- -------------------- 1.3/2.8 MB 39.2 kB/s eta 0:00:37
   ------------------- -------------------- 1.3/2.8 MB 39.2 kB/s eta 0:00:37
   ------------------- -------------------- 1.3/2.8 MB 39.2 kB/s eta 0:00:37
   ------------------- -------------------- 1.3/2.8 MB 39.2 kB/s eta 0:00:37
   ------------------- -------------------- 1.3/2.8 MB 39.2 kB/s eta 0:00:37
   ------------------- -------------------- 1.3/2.8 MB 39.2 kB/s eta 0:00:37
   ---------------------- ----------------- 1.6/2.8 MB 47.6 kB/s eta 0:00:25
   ---------------------- ----------------- 1.6/2.8 MB 47.6 kB/s eta 0:00:25
   ---------------------- ----------------- 1.6/2.8 MB 47.6 kB/s eta 0:00:25
   ---------------------- ----------------- 1.6/2.8 MB 47.6 kB/s eta 0:00:25
   ---------------------- ----------------- 1.6/2.8 MB 47.6 kB/s eta 0:00:25
   ---------------------- ----------------- 1.6/2.8 MB 47.6 kB/s eta 0:00:25
   ---------------------- ----------------- 1.6/2.8 MB 47.6 kB/s eta 0:00:25
   ---------------------- ----------------- 1.6/2.8 MB 47.6 kB/s eta 0:00:25
   ---------------------- ----------------- 1.6/2.8 MB 47.6 kB/s eta 0:00:25
   ---------------------- ----------------- 1.6/2.8 MB 47.6 kB/s eta 0:00:25
   ---------------------- ----------------- 1.6/2.8 MB 47.6 kB/s eta 0:00:25
   ---------------------- ----------------- 1.6/2.8 MB 47.6 kB/s eta 0:00:25
   ---------------------- ----------------- 1.6/2.8 MB 47.6 kB/s eta 0:00:25
   ---------------------- ----------------- 1.6/2.8 MB 47.6 kB/s eta 0:00:25
   ---------------------- ----------------- 1.6/2.8 MB 47.6 kB/s eta 0:00:25
   ---------------------- ----------------- 1.6/2.8 MB 47.6 kB/s eta 0:00:25
   ---------------------- ----------------- 1.6/2.8 MB 47.6 kB/s eta 0:00:25
   ---------------------- ----------------- 1.6/2.8 MB 47.6 kB/s eta 0:00:25
   ---------------------- ----------------- 1.6/2.8 MB 47.6 kB/s eta 0:00:25
   ---------------------- ----------------- 1.6/2.8 MB 47.6 kB/s eta 0:00:25
   ---------------------- ----------------- 1.6/2.8 MB 47.6 kB/s eta 0:00:25
   ---------------------- ----------------- 1.6/2.8 MB 47.6 kB/s eta 0:00:25
   ---------------------- ----------------- 1.6/2.8 MB 47.6 kB/s eta 0:00:25
   ---------------------- ----------------- 1.6/2.8 MB 47.6 kB/s eta 0:00:25
   ---------------------- ----------------- 1.6/2.8 MB 47.6 kB/s eta 0:00:25
   ---------------------- ----------------- 1.6/2.8 MB 47.6 kB/s eta 0:00:25
   ---------------------- ----------------- 1.6/2.8 MB 47.6 kB/s eta 0:00:25
   ---------------------- ----------------- 1.6/2.8 MB 47.6 kB/s eta 0:00:25
   ---------------------- ----------------- 1.6/2.8 MB 47.6 kB/s eta 0:00:25
   ---------------------- ----------------- 1.6/2.8 MB 47.6 kB/s eta 0:00:25
   ---------------------- ----------------- 1.6/2.8 MB 47.6 kB/s eta 0:00:25
   ---------------------- ----------------- 1.6/2.8 MB 47.6 kB/s eta 0:00:25

WARNING: Connection timed out while downloading.
WARNING: Attempting to resume incomplete download (262 kB/2.8 MB, attempt 1)

In [61]:

from sqlalchemy import create_engine
username = "postgres"
password = "mama"          
host = "localhost"
port = "5432"
database = "customer_behaviour"   

engine = create_engine(
    f'postgresql+psycopg2://{username}:{password}@{host}:{port}/{database}'
)
df.to_sql(
    name='customer',   # table name
    con=engine,
    if_exists='replace',      # replace/create table
    index=False
)

print("Connected Successfully")

Connected Successfully